// AUTO-GENERATED by scripts/sync-abis.mjs from contracts/out/NAVCalculator.sol/NAVCalculator.json. Do not edit.
export const navCalculatorAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "registry_",
        "type": "address",
        "internalType": "contract ITriplexRegistry"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getAllProducts",
    "inputs": [],
    "outputs": [
      {
        "name": "out",
        "type": "tuple[]",
        "internalType": "struct NAVCalculator.ProductView[]",
        "components": [
          {
            "name": "product",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "adapter",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "symbol",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "underlying",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "underlyingSymbol",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "isLong",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "targetLeverage",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minLeverage",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxLeverage",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "priceOk",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "price",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "navPerShare",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "leverage",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "exposure",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "collateralValue",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "debtValue",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "equity",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "ltv",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lltv",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "snapshotNav",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "snapshotPrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "snapshotTime",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "dailyReturn",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "underlyingDailyReturn",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "mintFeeBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "redeemFeeBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "mgmtFeeBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "supplyCapEquity",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "paused",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getProduct",
    "inputs": [
      {
        "name": "product",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "v",
        "type": "tuple",
        "internalType": "struct NAVCalculator.ProductView",
        "components": [
          {
            "name": "product",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "adapter",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "symbol",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "underlying",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "underlyingSymbol",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "isLong",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "targetLeverage",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minLeverage",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxLeverage",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "priceOk",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "price",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "navPerShare",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "leverage",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "exposure",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "collateralValue",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "debtValue",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "equity",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "ltv",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lltv",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "snapshotNav",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "snapshotPrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "snapshotTime",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "dailyReturn",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "underlyingDailyReturn",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "mintFeeBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "redeemFeeBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "mgmtFeeBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "supplyCapEquity",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "paused",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getProducts",
    "inputs": [
      {
        "name": "products",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "outputs": [
      {
        "name": "out",
        "type": "tuple[]",
        "internalType": "struct NAVCalculator.ProductView[]",
        "components": [
          {
            "name": "product",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "adapter",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "symbol",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "underlying",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "underlyingSymbol",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "isLong",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "targetLeverage",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minLeverage",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxLeverage",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "priceOk",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "price",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "navPerShare",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "leverage",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "exposure",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "collateralValue",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "debtValue",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "equity",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "ltv",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lltv",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "snapshotNav",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "snapshotPrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "snapshotTime",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "dailyReturn",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "underlyingDailyReturn",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "mintFeeBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "redeemFeeBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "mgmtFeeBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "supplyCapEquity",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "paused",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ITriplexRegistry"
      }
    ],
    "stateMutability": "view"
  }
] as const;
