#!/usr/bin/env node
// Copies contract ABIs from the Foundry build output (../contracts/out) into src/abi/*.ts.
// Usage: pnpm sync-abis   (run `forge build` in ../contracts first)
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, "../../contracts/out");
const abiDir = resolve(here, "../src/abi");

/** [solidity file, contract name, exported const name] */
const TARGETS = [
  ["LeveragedToken.sol", "LeveragedToken", "leveragedTokenAbi"],
  ["NAVCalculator.sol", "NAVCalculator", "navCalculatorAbi"],
  ["Rebalancer.sol", "Rebalancer", "rebalancerAbi"],
  ["MarketClock.sol", "MarketClock", "marketClockAbi"],
  ["ProjectTokenHooks.sol", "ProjectTokenHooks", "projectTokenHooksAbi"],
  ["FeeCollector.sol", "FeeCollector", "feeCollectorAbi"],
  ["LeveragedTokenFactory.sol", "LeveragedTokenFactory", "leveragedTokenFactoryAbi"],
  ["ComplianceRegistry.sol", "ComplianceRegistry", "complianceRegistryAbi"],
  ["ERC20.sol", "ERC20", "erc20Abi"],
];

if (!existsSync(outDir)) {
  console.error(`Foundry output not found at ${outDir}. Run: cd ../contracts && forge build`);
  process.exit(1);
}
mkdirSync(abiDir, { recursive: true });

const index = [];
for (const [file, contract, exportName] of TARGETS) {
  const src = join(outDir, file, `${contract}.json`);
  if (!existsSync(src)) {
    console.error(`Missing ${src}`);
    process.exit(1);
  }
  const { abi } = JSON.parse(readFileSync(src, "utf8"));
  const tsName = exportName.replace(/Abi$/, "");
  const body =
    `// AUTO-GENERATED by scripts/sync-abis.mjs from contracts/out/${file}/${contract}.json. Do not edit.\n` +
    `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(abiDir, `${tsName}.ts`), body);
  index.push(`export { ${exportName} } from "./${tsName}";`);
  console.log(`wrote src/abi/${tsName}.ts (${abi.length} entries)`);
}
writeFileSync(join(abiDir, "index.ts"), `// AUTO-GENERATED by scripts/sync-abis.mjs. Do not edit.\n${index.join("\n")}\n`);
